### ISSUE TITLE
Access to 10x cellranger-arc GEX raw h5 and ATAC framents files

### ISSUE THREAD

**Issue by vitkl** [linnarsson-lab/fetal_brain_multiomics#1]
Hi @camiel-m 

Huge congratulations on this paper! Very impressive work and an important resource. We are building foundational gene regulation models of human developmental tissues and including your atlas would be very helpful as a comprehensive reference of early brain development. 

To run our standardised workflows on all data and to use ATAC windows different from your study, we need 10x cellranger-arc output files for all individual reactions, specifically (** denotes essential):

- atac_fragments.tsv.gz  ** 
- atac_fragments.tsv.gz.tbi  
- filtered_feature_bc_matrix.h5  ** (not strictly essential if loom files already contain this data)
- raw_feature_bc_matrix.h5
- per_barcode_metrics.csv  
- summary.csv 

Would it be possible for you to share these files? These are all summaries and don't contain any donor-specific sequences.

I am also not sure if the files listed below contain all cells presented in the study rather than cell aggregates (pools). Could you please confirm?
[Pool_peaks.loom](https://storage.googleapis.com/linnarsson-lab-human/ATAC_dev/Pool_peaks.loom)
[Pool_peaks.agg.loom](https://storage.googleapis.com/linnarsson-lab-human/ATAC_dev/Pool_peaks.agg.loom)
[Pool_RNA.loom](https://storage.googleapis.com/linnarsson-lab-human/ATAC_dev/Pool_RNA.loom)
[Pool_RNA.agg.loom](https://storage.googleapis.com/linnarsson-lab-human/ATAC_dev/Pool_RNA.agg.loom)

Happy to reach out to you and Dr Linnarsson by email as well.

**Comment by camiel-m** [comment]
Hi vitkl, 'pool' in the file names refers to the data being pooled from sub-builds and they contain all cells from the study (minus filtered out cells). The *.agg.loom files are cluster aggregated files, i.e. one column per cluster with some aggregate measures like mean expression etc.

In regards to the 10X output files, we have those on our server but not currently shared anywhere. Please reach out to me over email and we can discuss a data transfer.

**Comment by camiel-m** [comment]
The README.md has now been updated with download instructions. Feel free to reopen if you are having issues accessing the data.
