### ISSUE TITLE
Request for Source Code of Function "compute_hypo_contrib"

### ISSUE THREAD

**Issue by shycheng** [linnarsson-lab/fetal_brain_multiomics#2]
Hi,

Thank you for your excellent work, which has been very helpful. I am particularly interested in the function "compute_hypo_contrib" mentioned in the notebook "DeepNeuron_example.ipynb." Unfortunately, I could not find its source code in the repository.

Could you kindly provide the source code for this function? It would be immensely helpful for my ongoing research.

Thank you for your consideration.

Best regards,

ShaoYun

**Comment by camiel-m** [comment]
Hi Shaoyun,

My apologies for the (very) late reply. The function call was indeed missing from utils and I added it here bc77c0b23315b674f4c55cd22b07b1e01439e1c3
